apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # Base64 encoded 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded 'password'
  POSTGRES_DB: Zmxhc2tfd2Vi  # Base64 encoded 'flask_web'
